package rules.triage.level1.hypoxemia

import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.VitalSignThresholds;
import com.ftn.model.Vitals;

rule "Detect hypoxemia"
when
    $patient : Patient()
    $vitals : Vitals($spo2 : spo2)
    eval(VitalSignThresholds.isHypoxemia($patient, $spo2))
    not Symptom(type == SymptomType.HYPOXEMIA)
then
    insert(new Symptom(SymptomType.HYPOXEMIA));
end
