package rules.triage.level1

import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.VitalSignThresholds;
import com.ftn.model.Vitals;

rule "Detect fever"
when
    $patient : Patient()
    $vitals : Vitals($temperature : temperature)
    eval(VitalSignThresholds.isFever($patient, $temperature))
    not Symptom(type == SymptomType.FEVER)
then
    insert(new Symptom(SymptomType.FEVER));
end
