package rules.triage.level1

import com.ftn.model.AgeCategory;
import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.Vitals;

rule "Detect tachycardia in senior"
when
    Patient(ageCategory == AgeCategory.SENIOR)
    Vitals(pulse > 90)
    not Symptom(type == SymptomType.TACHYCARDIA)
then
    insert(new Symptom(SymptomType.TACHYCARDIA));
end
