package rules.triage.level1.tachycardia

import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.Vitals;

rule "Detect tachycardia in infant"
when
    $patient : Patient(preterm == false, age == 0)
    eval($patient.getAgeInMonths() == null || $patient.getAgeInMonths() >= 1)
    Vitals(pulse > 140)
    not Symptom(type == SymptomType.TACHYCARDIA)
then
    insert(new Symptom(SymptomType.TACHYCARDIA));
end
