package rules.triage.level1

import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.Vitals;

rule "Detect tachycardia in newborn"
when
    $patient : Patient(preterm == false, age == 0)
    eval($patient.getAgeInMonths() != null && $patient.getAgeInMonths() < 1)
    Vitals(pulse > 160)
    not Symptom(type == SymptomType.TACHYCARDIA)
then
    insert(new Symptom(SymptomType.TACHYCARDIA));
end
