package rules.triage.level1

import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.VitalSignThresholds;
import com.ftn.model.Vitals;

rule "Detect hypotension"
when
    $patient : Patient()
    $vitals : Vitals($systolicBloodPressure : systolicBloodPressure)
    eval(VitalSignThresholds.isHypotension($patient, $systolicBloodPressure))
    not Symptom(type == SymptomType.HYPOTENSION)
then
    insert(new Symptom(SymptomType.HYPOTENSION));
end
