package rules.triage.level1

import com.ftn.model.AgeCategory;
import com.ftn.model.Patient;

rule "Classify patient by age"
    salience 1000
when
    $patient : Patient(ageCategory == null, $age : age)
then
    if ($age < 18) {
        $patient.setAgeCategory(AgeCategory.CHILD);
    } else if ($age <= 65) {
        $patient.setAgeCategory(AgeCategory.ADULT);
    } else {
        $patient.setAgeCategory(AgeCategory.SENIOR);
    }
    update($patient);
end
