package rules.triage.level1

import com.ftn.model.AgeCategory;
import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.Vitals;

rule "Detect hypotension"
when
    Patient($category : ageCategory != null)
    Vitals(
        ($category == AgeCategory.CHILD && systolicBloodPressure < 90) ||
        ($category == AgeCategory.ADULT && systolicBloodPressure < 100) ||
        ($category == AgeCategory.SENIOR && systolicBloodPressure < 110)
    )
    not Symptom(type == SymptomType.HYPOTENSION)
then
    insert(new Symptom(SymptomType.HYPOTENSION));
end
