package rules.triage.level1

import com.ftn.model.AgeCategory;
import com.ftn.model.Patient;
import com.ftn.model.Symptom;
import com.ftn.model.SymptomType;
import com.ftn.model.Vitals;

rule "Detect hypoxemia"
when
    Patient($category : ageCategory != null)
    Vitals(
        ($category == AgeCategory.CHILD && spo2 < 95) ||
        ($category == AgeCategory.ADULT && spo2 < 94) ||
        ($category == AgeCategory.SENIOR && spo2 < 92)
    )
    not Symptom(type == SymptomType.HYPOXEMIA)
then
    insert(new Symptom(SymptomType.HYPOXEMIA));
end
